# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/_code/fv/lab1_fv/lab1_fv.srcs/sources_1/ip/axi_timer_0/axi_timer_0.xci
# IP: The module: 'axi_timer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/_code/fv/lab1_fv/lab1_fv.gen/sources_1/ip/axi_timer_0/axi_timer_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_timer_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/_code/fv/lab1_fv/lab1_fv.gen/sources_1/ip/axi_timer_0/axi_timer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/_code/fv/lab1_fv/lab1_fv.srcs/sources_1/ip/axi_timer_0/axi_timer_0.xci
# IP: The module: 'axi_timer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/_code/fv/lab1_fv/lab1_fv.gen/sources_1/ip/axi_timer_0/axi_timer_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/_code/fv/lab1_fv/lab1_fv.gen/sources_1/ip/axi_timer_0/axi_timer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_timer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
